In [1]:
import pandas as pd
import re

In [2]:
csv = '/home/savage/Downloads/fifa21 raw data v2.csv'

In [3]:
df = pd.read_csv(csv, low_memory=False)

In [4]:
df.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [5]:
df.rename(columns = {'↓OVA': 'Overall Rating', "Weight": "Weight (kg)",
                     "Height": "Height (cm)", "Value": "Value (Euros)", "Wage": "Wage (Euros)"}, inplace=True)

In [6]:
df.drop([col for col in df.columns if col not in 
         ['Club','Overall Rating', 'Weight (kg)', 'Height (cm)', 
          'Name', 'Nationality', 'Value (Euros)', 'Wage (Euros)', 'Joined']], axis=1, inplace=True)

In [7]:
df

,Name,Nationality,Overall Rating,Club,Height (cm),Weight (kg),Joined,Value (Euros),Wage (Euros)
0,L. Messi,Argentina,93,\n\n\n\nFC Barcelona,170cm,72kg,"Jul 1, 2004",€103.5M,€560K
1,Cristiano Ronaldo,Portugal,92,\n\n\n\nJuventus,187cm,83kg,"Jul 10, 2018",€63M,€220K
2,J. Oblak,Slovenia,91,\n\n\n\nAtlético Madrid,188cm,87kg,"Jul 16, 2014",€120M,€125K
3,K. De Bruyne,Belgium,91,\n\n\n\nManchester City,181cm,70kg,"Aug 30, 2015",€129M,€370K
4,Neymar Jr,Brazil,91,\n\n\n\nParis Saint-Germain,175cm,68kg,"Aug 3, 2017",€132M,€270K
...,...,...,...,...,...,...,...,...,...
18974,Xia Ao,China PR,47,\n\n\n\nWuhan Zall,178cm,66kg,"Jul 13, 2018",€100K,€1K
18975,B. Hough,England,47,\n\n\n\nOldham Athletic,175cm,65kg,"Aug 1, 2020",€130K,€500
18976,R. McKinley,England,47,\n\n\n\nDerry City,179cm,74kg,"Mar 8, 2019",€120K,€500
18977,Wang Zhen'ao,China PR,47,\n\n\n\nDalian YiFang FC,175cm,69kg,"Sep 22, 2020",€100K,€2K
18978,Zhou Xiao,China PR,47,\n\n\n\nDalian YiFang FC,188cm,75kg,"Jul 29, 2019",€100K,€1K

In [8]:
df.head()['Club']

0           \n\n\n\nFC Barcelona
1               \n\n\n\nJuventus
2        \n\n\n\nAtlético Madrid
3        \n\n\n\nManchester City
4    \n\n\n\nParis Saint-Germain
Name: Club, dtype: object

In [9]:
df['Club'] = df['Club'].map(lambda club: re.sub(r'(\n)+','', club), na_action=None)

In [10]:
df.head()['Club']

0           FC Barcelona
1               Juventus
2        Atlético Madrid
3        Manchester City
4    Paris Saint-Germain
Name: Club, dtype: object

In [11]:
df.loc[0]

Name                  L. Messi
Nationality          Argentina
Overall Rating              93
Club              FC Barcelona
Height (cm)              170cm
Weight (kg)               72kg
Joined             Jul 1, 2004
Value (Euros)          €103.5M
Wage (Euros)             €560K
Name: 0, dtype: object

In [12]:
df.loc[0, 'Height (cm)': 'Weight (kg)']

Height (cm)    170cm
Weight (kg)     72kg
Name: 0, dtype: object

In [13]:
re.sub(r'cm','', df.loc[0, 'Height (cm)'])

'170'

In [14]:
re.sub(r'kg','', df.loc[0, 'Weight (kg)'])

'72'

In [15]:
df['Height (cm)'] = df['Height (cm)'].map(lambda height: re.sub(r'cm','', height), na_action=None)
df['Weight (kg)'] = df['Weight (kg)'].map(lambda weight: re.sub(r'kg','', weight), na_action=None)

In [16]:
df

,Name,Nationality,Overall Rating,Club,Height (cm),Weight (kg),Joined,Value (Euros),Wage (Euros)
0,L. Messi,Argentina,93,FC Barcelona,170,72,"Jul 1, 2004",€103.5M,€560K
1,Cristiano Ronaldo,Portugal,92,Juventus,187,83,"Jul 10, 2018",€63M,€220K
2,J. Oblak,Slovenia,91,Atlético Madrid,188,87,"Jul 16, 2014",€120M,€125K
3,K. De Bruyne,Belgium,91,Manchester City,181,70,"Aug 30, 2015",€129M,€370K
4,Neymar Jr,Brazil,91,Paris Saint-Germain,175,68,"Aug 3, 2017",€132M,€270K
...,...,...,...,...,...,...,...,...,...
18974,Xia Ao,China PR,47,Wuhan Zall,178,66,"Jul 13, 2018",€100K,€1K
18975,B. Hough,England,47,Oldham Athletic,175,65,"Aug 1, 2020",€130K,€500
18976,R. McKinley,England,47,Derry City,179,74,"Mar 8, 2019",€120K,€500
18977,Wang Zhen'ao,China PR,47,Dalian YiFang FC,175,69,"Sep 22, 2020",€100K,€2K
18978,Zhou Xiao,China PR,47,Dalian YiFang FC,188,75,"Jul 29, 2019",€100K,€1K

In [17]:
df.loc[0, 'Value (Euros)'][1:-1]

'103.5'

In [18]:
df.loc[0, 'Value (Euros)'][-1]

'M'

In [19]:
def make_numerical(value):
    numerical = value[1:-1]
    if numerical == '':
        return 0
    suffix = value[-1]
    if suffix == 'M':
        number = float(numerical) * 1000000
    else:
        number = float(numerical) * 1000
    return number

In [20]:
make_numerical(df.loc[0, 'Value (Euros)'])

103500000.0

In [21]:
df['Value (Euros)'] = df['Value (Euros)'].map(make_numerical, na_action=None)

In [22]:
df['Wage (Euros)'] = df['Wage (Euros)'].map(make_numerical, na_action=None)

In [23]:
df

,Name,Nationality,Overall Rating,Club,Height (cm),Weight (kg),Joined,Value (Euros),Wage (Euros)
0,L. Messi,Argentina,93,FC Barcelona,170,72,"Jul 1, 2004",103500000.0,560000.0
1,Cristiano Ronaldo,Portugal,92,Juventus,187,83,"Jul 10, 2018",63000000.0,220000.0
2,J. Oblak,Slovenia,91,Atlético Madrid,188,87,"Jul 16, 2014",120000000.0,125000.0
3,K. De Bruyne,Belgium,91,Manchester City,181,70,"Aug 30, 2015",129000000.0,370000.0
4,Neymar Jr,Brazil,91,Paris Saint-Germain,175,68,"Aug 3, 2017",132000000.0,270000.0
...,...,...,...,...,...,...,...,...,...
18974,Xia Ao,China PR,47,Wuhan Zall,178,66,"Jul 13, 2018",100000.0,1000.0
18975,B. Hough,England,47,Oldham Athletic,175,65,"Aug 1, 2020",130000.0,50000.0
18976,R. McKinley,England,47,Derry City,179,74,"Mar 8, 2019",120000.0,50000.0
18977,Wang Zhen'ao,China PR,47,Dalian YiFang FC,175,69,"Sep 22, 2020",100000.0,2000.0
18978,Zhou Xiao,China PR,47,Dalian YiFang FC,188,75,"Jul 29, 2019",100000.0,1000.0

In [24]:
type(df.loc[0,'Height (cm)'])

str

In [25]:
s = df['Height (cm)'].str.contains(r'\d\'(\d)*(\")*')

/tmp/ipykernel_41271/2670347789.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  s = df['Height (cm)'].str.contains(r'\d\'(\d)*(\")*')

In [26]:
non_cm_heights_idx = [idx for idx in range(len(s)) if s[idx] == True]

In [27]:
df.loc[non_cm_heights_idx]

,Name,Nationality,Overall Rating,Club,Height (cm),Weight (kg),Joined,Value (Euros),Wage (Euros)
793,Moyá,Spain,78,Real Sociedad,"6'2""",183lbs,"Feb 27, 2018",1700000.0,15000.0
847,M. Škrtel,Slovakia,78,Medipol Başakşehir FK,"6'3""",179lbs,"Aug 20, 2020",3100000.0,26000.0
848,B. Dost,Netherlands,78,Eintracht Frankfurt,"6'5""",183lbs,"Aug 26, 2019",9500000.0,33000.0
860,Sérgio Oliveira,Portugal,78,FC Porto,"5'11""",172lbs,"Jul 1, 2015",10500000.0,16000.0
861,M. Hitz,Switzerland,78,Borussia Dortmund,"6'4""",196lbs,"Jul 1, 2018",6500000.0,39000.0
862,Laguardia,Spain,78,Deportivo Alavés,"6'1""",176lbs,"Jul 11, 2014",8500000.0,25000.0
863,Y. El Arabi,Morocco,78,Olympiacos CFP,"6'0""",185lbs,"Jul 6, 2019",6500000.0,50000.0
864,G. Pezzella,Argentina,78,Fiorentina,"6'1""",179lbs,"Jul 1, 2018",8500000.0,50000.0
865,R. Rodríguez,Switzerland,78,Torino,"5'11""",170lbs,"Aug 19, 2020",9000000.0,41000.0
866,Herrerín,Spain,78,Athletic Club de Bilbao,"6'2""",196lbs,"Jul 1, 2012",6500000.0,19000.0
867,E. Stevens,Republic of Ireland,78,Sheffield United,"6'0""",172lbs,"Jul 1, 2017",8500000.0,37000.0
868,C. Wood,New Zealand,78,Burnley,"6'3""",203lbs,"Aug 21, 2017",10500000.0,62000.0
869,A. Kokorin,Russia,78,Spartak Moscow,"6'0""",183lbs,"Aug 2, 2020",10500000.0,63000.0
871,L. Rodríguez,Mexico,78,Tigres U.A.N.L.,"5'10""",168lbs,"Jun 9, 2016",8500000.0,46000.0
872,A. Westwood,England,78,Burnley,"5'9""",161lbs,"Jan 31, 2017",8500000.0,50000.0
873,C. Wilson,England,78,Newcastle United,"5'11""",146lbs,"Sep 7, 2020",10500000.0,48000.0
874,M. Lanzini,Argentina,78,West Ham United,"5'6""",130lbs,"Jul 1, 2016",12000000.0,43000.0
875,K. Boateng,Ghana,78,AC Monza,"6'1""",190lbs,"Sep 28, 2020",6500000.0,7000.0
876,S. Lulić,Bosnia Herzegovina,78,Lazio,"6'0""",172lbs,"Jul 1, 2011",5000000.0,56000.0
877,A. Mirante,Italy,78,Roma,"6'4""",174lbs,"Jul 1, 2018",1700000.0,50000.0
878,L. Acosta,Argentina,78,Club Atlético Lanús,"5'7""",148lbs,"Jul 13, 2013",8000000.0,24000.0
879,M. Suárez,Argentina,78,River Plate,"6'0""",165lbs,"Jan 27, 2019",8500000.0,21000.0
880,Rafael Carioca,Brazil,78,Tigres U.A.N.L.,"5'11""",172lbs,"Aug 25, 2017",8000000.0,44000.0
881,M. Musacchio,Argentina,78,Milan,"5'11""",161lbs,"Jul 1, 2017",8500000.0,38000.0
883,Víctor Díaz,Spain,78,Granada CF,"6'0""",159lbs,"Jul 4, 2017",6500000.0,26000.0
884,P. Diop,Senegal,78,SD Eibar,"5'10""",170lbs,"Jan 1, 2018",4000000.0,28000.0
885,E. Capoue,France,78,Watford,"6'3""",192lbs,"Jul 6, 2015",8000000.0,20000.0
886,F. Caicedo,Ecuador,78,Lazio,"6'0""",181lbs,"Aug 2, 2017",9500000.0,60000.0
887,P. Piatti,Argentina,78,Toronto FC,"5'4""",139lbs,"Feb 7, 2020",9000000.0,11000.0
888,A. Candreva,Italy,78,Sampdoria,"5'11""",154lbs,"Aug 3, 2016",6500000.0,23000.0
889,M. Debuchy,France,78,AS Saint-Étienne,"5'9""",168lbs,"Jan 31, 2018",3600000.0,32000.0
890,C. Tévez,Argentina,78,Boca Juniors,"5'7""",170lbs,"Jan 6, 2018",3700000.0,16000.0
891,D. Criscito,Italy,78,Genoa,"6'0""",165lbs,"Jul 1, 2018",4700000.0,18000.0
892,J. Sosa,Argentina,78,Fenerbahçe SK,"5'10""",157lbs,"Aug 21, 2020",4300000.0,47000.0
893,Jorge Molina,Spain,78,Granada CF,"6'2""",159lbs,"Aug 24, 2020",3700000.0,24000.0
894,Andrés Fernández,Spain,78,SD Huesca,"6'2""",181lbs,"Aug 28, 2020",5500000.0,20000.0
895,José Fonte,Portugal,78,LOSC Lille,"6'3""",179lbs,"Jul 15, 2018",2100000.0,24000.0
896,A. Guardado,Mexico,78,Real Betis,"5'7""",148lbs,"Jul 7, 2017",6000000.0,26000.0
897,V. Moses,Nigeria,78,Chelsea,"5'10""",170lbs,"Aug 24, 2012",10000000.0,84000.0
898,L. López,Argentina,78,Racing Club,"5'9""",163lbs,"Jan 4, 2016",3700000.0,18000.0

In [28]:
non_cm_heights_idx[0]

793

In [29]:
def to_cm_str(value):
    if re.match(r'^\d+$', value):
        return value
    height_components = value[::2]
    feet_in_inches = int(height_components[0]) * 12 + int(height_components[1])
    return str(round(feet_in_inches * 2.54))

In [30]:
def to_kg_str(value):
    if re.match(r'^\d+$',value):
        return value
    return str(round(int(value[:-3]) * 0.45359237))

In [31]:
to_cm_str(df.loc[non_cm_heights_idx[0], "Height (cm)"])

'188'

In [32]:
df['Height (cm)'] = df['Height (cm)'].map(to_cm_str, na_action=None)
df['Weight (kg)'] = df['Weight (kg)'].map(to_kg_str, na_action=None)

In [33]:
df.loc[non_cm_heights_idx]

,Name,Nationality,Overall Rating,Club,Height (cm),Weight (kg),Joined,Value (Euros),Wage (Euros)
793,Moyá,Spain,78,Real Sociedad,188,83,"Feb 27, 2018",1700000.0,15000.0
847,M. Škrtel,Slovakia,78,Medipol Başakşehir FK,190,81,"Aug 20, 2020",3100000.0,26000.0
848,B. Dost,Netherlands,78,Eintracht Frankfurt,196,83,"Aug 26, 2019",9500000.0,33000.0
860,Sérgio Oliveira,Portugal,78,FC Porto,155,78,"Jul 1, 2015",10500000.0,16000.0
861,M. Hitz,Switzerland,78,Borussia Dortmund,193,89,"Jul 1, 2018",6500000.0,39000.0
862,Laguardia,Spain,78,Deportivo Alavés,185,80,"Jul 11, 2014",8500000.0,25000.0
863,Y. El Arabi,Morocco,78,Olympiacos CFP,183,84,"Jul 6, 2019",6500000.0,50000.0
864,G. Pezzella,Argentina,78,Fiorentina,185,81,"Jul 1, 2018",8500000.0,50000.0
865,R. Rodríguez,Switzerland,78,Torino,155,77,"Aug 19, 2020",9000000.0,41000.0
866,Herrerín,Spain,78,Athletic Club de Bilbao,188,89,"Jul 1, 2012",6500000.0,19000.0
867,E. Stevens,Republic of Ireland,78,Sheffield United,183,78,"Jul 1, 2017",8500000.0,37000.0
868,C. Wood,New Zealand,78,Burnley,190,92,"Aug 21, 2017",10500000.0,62000.0
869,A. Kokorin,Russia,78,Spartak Moscow,183,83,"Aug 2, 2020",10500000.0,63000.0
871,L. Rodríguez,Mexico,78,Tigres U.A.N.L.,155,76,"Jun 9, 2016",8500000.0,46000.0
872,A. Westwood,England,78,Burnley,175,73,"Jan 31, 2017",8500000.0,50000.0
873,C. Wilson,England,78,Newcastle United,155,66,"Sep 7, 2020",10500000.0,48000.0
874,M. Lanzini,Argentina,78,West Ham United,168,59,"Jul 1, 2016",12000000.0,43000.0
875,K. Boateng,Ghana,78,AC Monza,185,86,"Sep 28, 2020",6500000.0,7000.0
876,S. Lulić,Bosnia Herzegovina,78,Lazio,183,78,"Jul 1, 2011",5000000.0,56000.0
877,A. Mirante,Italy,78,Roma,193,79,"Jul 1, 2018",1700000.0,50000.0
878,L. Acosta,Argentina,78,Club Atlético Lanús,170,67,"Jul 13, 2013",8000000.0,24000.0
879,M. Suárez,Argentina,78,River Plate,183,75,"Jan 27, 2019",8500000.0,21000.0
880,Rafael Carioca,Brazil,78,Tigres U.A.N.L.,155,78,"Aug 25, 2017",8000000.0,44000.0
881,M. Musacchio,Argentina,78,Milan,155,73,"Jul 1, 2017",8500000.0,38000.0
883,Víctor Díaz,Spain,78,Granada CF,183,72,"Jul 4, 2017",6500000.0,26000.0
884,P. Diop,Senegal,78,SD Eibar,155,77,"Jan 1, 2018",4000000.0,28000.0
885,E. Capoue,France,78,Watford,190,87,"Jul 6, 2015",8000000.0,20000.0
886,F. Caicedo,Ecuador,78,Lazio,183,82,"Aug 2, 2017",9500000.0,60000.0
887,P. Piatti,Argentina,78,Toronto FC,163,63,"Feb 7, 2020",9000000.0,11000.0
888,A. Candreva,Italy,78,Sampdoria,155,70,"Aug 3, 2016",6500000.0,23000.0
889,M. Debuchy,France,78,AS Saint-Étienne,175,76,"Jan 31, 2018",3600000.0,32000.0
890,C. Tévez,Argentina,78,Boca Juniors,170,77,"Jan 6, 2018",3700000.0,16000.0
891,D. Criscito,Italy,78,Genoa,183,75,"Jul 1, 2018",4700000.0,18000.0
892,J. Sosa,Argentina,78,Fenerbahçe SK,155,71,"Aug 21, 2020",4300000.0,47000.0
893,Jorge Molina,Spain,78,Granada CF,188,72,"Aug 24, 2020",3700000.0,24000.0
894,Andrés Fernández,Spain,78,SD Huesca,188,82,"Aug 28, 2020",5500000.0,20000.0
895,José Fonte,Portugal,78,LOSC Lille,190,81,"Jul 15, 2018",2100000.0,24000.0
896,A. Guardado,Mexico,78,Real Betis,170,67,"Jul 7, 2017",6000000.0,26000.0
897,V. Moses,Nigeria,78,Chelsea,155,77,"Aug 24, 2012",10000000.0,84000.0
898,L. López,Argentina,78,Racing Club,175,74,"Jan 4, 2016",3700000.0,18000.0

In [34]:
df.astype({'Height (cm)': 'int32', 'Weight (kg)': 'int32', 'Value (Euros)': 'float64', 'Wage (Euros)': 'float64' })

,Name,Nationality,Overall Rating,Club,Height (cm),Weight (kg),Joined,Value (Euros),Wage (Euros)
0,L. Messi,Argentina,93,FC Barcelona,170,72,"Jul 1, 2004",103500000.0,560000.0
1,Cristiano Ronaldo,Portugal,92,Juventus,187,83,"Jul 10, 2018",63000000.0,220000.0
2,J. Oblak,Slovenia,91,Atlético Madrid,188,87,"Jul 16, 2014",120000000.0,125000.0
3,K. De Bruyne,Belgium,91,Manchester City,181,70,"Aug 30, 2015",129000000.0,370000.0
4,Neymar Jr,Brazil,91,Paris Saint-Germain,175,68,"Aug 3, 2017",132000000.0,270000.0
...,...,...,...,...,...,...,...,...,...
18974,Xia Ao,China PR,47,Wuhan Zall,178,66,"Jul 13, 2018",100000.0,1000.0
18975,B. Hough,England,47,Oldham Athletic,175,65,"Aug 1, 2020",130000.0,50000.0
18976,R. McKinley,England,47,Derry City,179,74,"Mar 8, 2019",120000.0,50000.0
18977,Wang Zhen'ao,China PR,47,Dalian YiFang FC,175,69,"Sep 22, 2020",100000.0,2000.0
18978,Zhou Xiao,China PR,47,Dalian YiFang FC,188,75,"Jul 29, 2019",100000.0,1000.0

In [35]:
df.loc[non_cm_heights_idx]

,Name,Nationality,Overall Rating,Club,Height (cm),Weight (kg),Joined,Value (Euros),Wage (Euros)
793,Moyá,Spain,78,Real Sociedad,188,83,"Feb 27, 2018",1700000.0,15000.0
847,M. Škrtel,Slovakia,78,Medipol Başakşehir FK,190,81,"Aug 20, 2020",3100000.0,26000.0
848,B. Dost,Netherlands,78,Eintracht Frankfurt,196,83,"Aug 26, 2019",9500000.0,33000.0
860,Sérgio Oliveira,Portugal,78,FC Porto,155,78,"Jul 1, 2015",10500000.0,16000.0
861,M. Hitz,Switzerland,78,Borussia Dortmund,193,89,"Jul 1, 2018",6500000.0,39000.0
862,Laguardia,Spain,78,Deportivo Alavés,185,80,"Jul 11, 2014",8500000.0,25000.0
863,Y. El Arabi,Morocco,78,Olympiacos CFP,183,84,"Jul 6, 2019",6500000.0,50000.0
864,G. Pezzella,Argentina,78,Fiorentina,185,81,"Jul 1, 2018",8500000.0,50000.0
865,R. Rodríguez,Switzerland,78,Torino,155,77,"Aug 19, 2020",9000000.0,41000.0
866,Herrerín,Spain,78,Athletic Club de Bilbao,188,89,"Jul 1, 2012",6500000.0,19000.0
867,E. Stevens,Republic of Ireland,78,Sheffield United,183,78,"Jul 1, 2017",8500000.0,37000.0
868,C. Wood,New Zealand,78,Burnley,190,92,"Aug 21, 2017",10500000.0,62000.0
869,A. Kokorin,Russia,78,Spartak Moscow,183,83,"Aug 2, 2020",10500000.0,63000.0
871,L. Rodríguez,Mexico,78,Tigres U.A.N.L.,155,76,"Jun 9, 2016",8500000.0,46000.0
872,A. Westwood,England,78,Burnley,175,73,"Jan 31, 2017",8500000.0,50000.0
873,C. Wilson,England,78,Newcastle United,155,66,"Sep 7, 2020",10500000.0,48000.0
874,M. Lanzini,Argentina,78,West Ham United,168,59,"Jul 1, 2016",12000000.0,43000.0
875,K. Boateng,Ghana,78,AC Monza,185,86,"Sep 28, 2020",6500000.0,7000.0
876,S. Lulić,Bosnia Herzegovina,78,Lazio,183,78,"Jul 1, 2011",5000000.0,56000.0
877,A. Mirante,Italy,78,Roma,193,79,"Jul 1, 2018",1700000.0,50000.0
878,L. Acosta,Argentina,78,Club Atlético Lanús,170,67,"Jul 13, 2013",8000000.0,24000.0
879,M. Suárez,Argentina,78,River Plate,183,75,"Jan 27, 2019",8500000.0,21000.0
880,Rafael Carioca,Brazil,78,Tigres U.A.N.L.,155,78,"Aug 25, 2017",8000000.0,44000.0
881,M. Musacchio,Argentina,78,Milan,155,73,"Jul 1, 2017",8500000.0,38000.0
883,Víctor Díaz,Spain,78,Granada CF,183,72,"Jul 4, 2017",6500000.0,26000.0
884,P. Diop,Senegal,78,SD Eibar,155,77,"Jan 1, 2018",4000000.0,28000.0
885,E. Capoue,France,78,Watford,190,87,"Jul 6, 2015",8000000.0,20000.0
886,F. Caicedo,Ecuador,78,Lazio,183,82,"Aug 2, 2017",9500000.0,60000.0
887,P. Piatti,Argentina,78,Toronto FC,163,63,"Feb 7, 2020",9000000.0,11000.0
888,A. Candreva,Italy,78,Sampdoria,155,70,"Aug 3, 2016",6500000.0,23000.0
889,M. Debuchy,France,78,AS Saint-Étienne,175,76,"Jan 31, 2018",3600000.0,32000.0
890,C. Tévez,Argentina,78,Boca Juniors,170,77,"Jan 6, 2018",3700000.0,16000.0
891,D. Criscito,Italy,78,Genoa,183,75,"Jul 1, 2018",4700000.0,18000.0
892,J. Sosa,Argentina,78,Fenerbahçe SK,155,71,"Aug 21, 2020",4300000.0,47000.0
893,Jorge Molina,Spain,78,Granada CF,188,72,"Aug 24, 2020",3700000.0,24000.0
894,Andrés Fernández,Spain,78,SD Huesca,188,82,"Aug 28, 2020",5500000.0,20000.0
895,José Fonte,Portugal,78,LOSC Lille,190,81,"Jul 15, 2018",2100000.0,24000.0
896,A. Guardado,Mexico,78,Real Betis,170,67,"Jul 7, 2017",6000000.0,26000.0
897,V. Moses,Nigeria,78,Chelsea,155,77,"Aug 24, 2012",10000000.0,84000.0
898,L. López,Argentina,78,Racing Club,175,74,"Jan 4, 2016",3700000.0,18000.0

In [36]:
type(df.loc[0, 'Joined'])

str